### ISSUE TITLE
3.1.3 Bázisosztályok keresése

### ISSUE THREAD

**Issue by marcibaumel** [marcibaumel/SpeedCards#83]

**Comment by MrDxD-SoulAdmin** [comment]
Main/CardObject/OptionsViewController/MainMenu/PlayController/Rergister/user/

**Comment by kzsofia12** [comment]
<p>
        Bázisosztálynak nevezzük azt az osztályt amely osztálynak nincs ősosztálya
    </p>
    <ul>
        <u>A szoftverünkben találéható bázisosztályok:</u>
        <li>
            <u>Main Osztály:</u>
            <p>
                A main osztály felelős az összes többi osztály egybegyűjtéséért ,meghívásáért valamint kezeléésért.
            </p>
        </li>
        <li>
            <u>CardObject osztály:</u>
            <p>
                A CardObject osztály felelős a lerakott és a kézben lévő lapok managgeléséért.
            </p>
        </li>
        <li>
            <u>OptionsViewController osztály:</u>
            <p>
                Az OptionsViewController a beállítások megjelenítésésért és kezeléésért felelős.
            </p>
        </li>
        <li>
            <u>MainMenuViewController osztály:</u>
            <p>
                A MainMenuViewController a szoftver elindítása után megjelenő menürendszer megjelenítését és kezeléset végzi.
            </p>
        </li>
        <li>
            <u>PlayController osztály:</u>
            <p>
                A PlayController osztály felelős a játékmenet kezeléséért és a lapok valamint a userdaták betöltéséért egy-egy meccs során.
            </p>
        </li>
        <li>
            <u>Register osztály:</u>
            <p>
                A Register osztály az eddig még adatbázisban nem lévő(nem regisztrált) usereket heklyezi bele az adatbázizba(regisztráltatja).
            </p>
        </li>
        <li>
            <u>User Osztály:</u>
            <p>
                Az User osztály a userekadatait és beállításait hivatott kezelni és controllálni.
            </p>
        </li>
    </ul>

**Comment by kzsofia12** [comment]
<body>
    <h1>3.1.3 Bázisosztályok Keresése</h1>
    <p>
        Bázisosztálynak nevezzük azt az osztályt amely osztálynak nincs ősosztálya
    </p>
    <ul>
        <u>A szoftverünkben találéható bázisosztályok:</u>
        <li>
            <u>Main Osztály:</u>
            <p>
                A main osztály felelős az összes többi osztály egybegyűjtéséért ,meghívásáért valamint kezeléésért.
            </p>
        </li>
        <li>
            <u>CardObject osztály:</u>
            <p>
                A CardObject osztály felelős a lerakott és a kézben lévő lapok managgeléséért.
            </p>
        </li>
        <li>
            <u>OptionsViewController osztály:</u>
            <p>
                Az OptionsViewController a beállítások megjelenítésésért és kezeléésért felelős.
            </p>
        </li>
        <li>
            <u>MainMenuViewController osztály:</u>
            <p>
                A MainMenuViewController a szoftver elindítása után megjelenő menürendszer megjelenítését és kezeléset végzi.
            </p>
        </li>
        <li>
            <u>PlayController osztály:</u>
            <p>
                A PlayController osztály felelős a játékmenet kezeléséért és a lapok valamint a userdaták betöltéséért egy-egy meccs során.
            </p>
        </li>
        <li>
            <u>Register osztály:</u>
            <p>
                A Register osztály az eddig még adatbázisban nem lévő(nem regisztrált) usereket heklyezi bele az adatbázizba(regisztráltatja).
            </p>
        </li>
        <li>
            <u>User Osztály:</u>
            <p>
                Az User osztály a userekadatait és beállításait hivatott kezelni és controllálni.
            </p>
        </li>
    </ul>
</body>

**Comment by MrDxD-SoulAdmin** [comment]
0.5óra
