### ISSUE TITLE
3.1.2 Attribútumok azonosítása

### ISSUE THREAD

**Issue by marcibaumel** [marcibaumel/SpeedCards#84]

**Comment by MrDxD-SoulAdmin** [comment]
<body>
    <u>Osztályok és atribútumok:</u>
    <ul>
        <li>
            <u>User osztály:</u>
            <p>
                private, mert a többi osztálynak nem kelll látni csak az adatait kell kezelni , és ezeket pedig a getter/setter metódusokkal le lehet végezni.
            </p>
        </li>
        <li>
            <u>Level Osztaly:</u>
            <p>Protected, mert nem minden osztálynak kell látni és kezelni kizálólag a PlayerController és a user osztálynak.</p>
        </li>
        <li>
            <u>CardObject Osztály:</u>
            <p>
                Public, mivel a program majdnem minden egyes elemének tudnia kell adatokat egyezeteni és kezelni.
            </p>
        </li>
        <li>
            <u>Hand osztály:</u>
            <p>
                Protected, mert kizárólag a dealer osztálynak kell tudnia kezelni, mert ha z user interakciót végez akkor azt a dealer osztályon keresztül teszi.
            </p>
        </li>
        <li>
            <u>EffectCard Object Osztály:</u>
            <p>
                public, mert azt a játék menet során a kezelő osztályoknak tudnia kell kezelni.
            </p>
        </li>
        <li>
            <u>SoundManager osztály:</u>
            <p>
                protected, mivel ezt az osztályt a OptionsViewController osztályon keresztül érjük el és nem közvetlen eléréssel.
            </p>
        </li>
        <li>
            <u>GroundCardObject Osztály:</u>
            <p>
                private, mert ezt csak a dealer tudja kezelni és semmi más nem férhet hozzá mivel ezt a dealer helyezi le a játék menet elején.
            </p>
        </li>
        <li>
            <u>AirCardObject Osztály:</u>
            <p>
                private, mert ezt csak a dealer tudja kezelni és semmi más nem férhet hozzá mivel ezt a dealer helyezi le a játék menet elején.
            </p>
        </li>
        <li>
            <u>Dealer Osztály:</u>
            <p>
                Private, mivel ehhez az osztályhoz senkinek nem szabad hozzájutni mivel akkor hiba keletkezne a program futása során.
            </p>
        </li>
        <li>
            <u>Deck Osztály:</u>
            <p>
                private, mivel ehhez az osztályhoz közvetlenül nem férhet hozzá senki.
            </p>
        </li>
        <li>
            <u>DbContext Osztály:</u>
            <p>
                private, mert ez az osztály kezeli az adatbázis és a program közötti kommunikációt és változás végzetes hibákat okozhat az adatbázisban.
            </p>
        </li>
        <li>
            <u>CardUnitOfWork Osztály:</u>
            <p>
                protected, mert ez az osztály fogja létesíteni a kapcsolatot az lapok adatait kérő osztályok és adatbázis között.
            </p>
        </li>
        <li>
            <u>UserUnitOfWork Osztály:</u>
            <p>
                protected, mert ez az osztály fogja létesíteni a kapcsolatot az user adatait kérő osztályok és adatbázis között.
            </p>
        </li>
        <li>
            <u>ShopUnitOfWork Osztály:</u>
            <p>protected, mert ez az osztály fogja létesíteni a kapcsolatot az user adatait kérő osztályok és adatbázis között.</p>
        </li>
        <li>
            <u>UserLoginController Osztály:</u>
            <p>
                private , mert ő csak az adatbázissal kommunikál és senkinek nem szabad látnia mivel, akkor kileshetőek a usernevek és passwd-k
            </p>
        </li>
        <li>
            <u>RegistrationController Osztály:</u>
            <p>protected, mivel itt az adatbázisba történik adat bevitel.</p>
        </li>
        <li>
            <u>MainMenuViewController Osztály:</u>
            <p>
                public, mivel ehhez szabad hozzáférés van mivel ez a fő GUI felület.
            </p>
        </li>
        <li>
            <u>HandController Osztály:</u>
            <p>
                private, mert ez az osztály kezeli a játékosr kezében lévő lepokat.
            </p>
        </li>
        <li>
            <u>OptionsViewController Osztály:</u>
            <p>
                protected, mert itt érhetőek el a beállítások viszont csak bizonyos osztályoknak kell csak látni és kezelni.
            </p>
        </li>
        <li>
            <u>PlayGroundViewController:</u>
            <p>
                public, mivel ő a játék kinézetéért felel csak semmilyen adatot nem kezel.
            </p>
        </li>
        <li>
            <u>PlayController Osztály:</u>
            <p>
                public, mivel ő felelős az osztályok közötti kommunikáció, és adatcsere lebonyolításáért.
            </p>
        </li>
        <li>
            <u>CardDescriptionController osztály:</u>
            <p>
                publik, mert mindenki hozzáférhet a kártyaleírásokhoz.
            </p>
        </li>
        <li>
            <u>ShopController osztály:</u>
            <p>
                protected, mert ehhez az osztályhoz csak az OptionsViewController en keresztül férhetünk hozzá.
            </p>
        </li>
        <li>
            <u>UserData Managger:</u>
            <p>
                private, mert a user adatait senki nem láthatja az useren kívűl.
            </p>
        </li>
        <li>
            <u>OnGroundCardObject Osztály:</u>
            <p>
                protected, mivel ehhez az osztályhoz csak a PlayControlleren keresztül férhetünk hozzá.
            </p>
        </li>
        <li>
            <u>DestroyedCardObject Osztály:</u>
            <p>Protected, mert ez az osztály is csak a PlayControlleren keresztül érjük el.</p>
        </li>
    </ul>
</body>

**Comment by MrDxD-SoulAdmin** [comment]
<body>
    <u>Osztályok és atribútumok:</u>
    <ul>
        <li>
            <u>User osztály:</u>
            <p>
                FID : INT<br>Name : STRING<br>Password : STRING<br>Birthday : DATE<br> Permisson : ENUM<br>
            </p>
        </li>
        <li>
            <u>Level Osztaly:</u>
            <p>
                WinExp : INT<br> LoseExp : INT<br> Multiplier : DOUBLE<br>
            </p>
        </li>
        <li>
            <u>CardObject Osztály:</u>
            <P>
                DefPoint : INT<br> AtcPoint : INT<br> HealthPoint: INT<br> Destroyed : BOOLEAN<br>
            </P>
        </li>
        <li>
            <u>Hand osztály:</u>
            <P>
                CardDb : INT<br> Cards : INT[5]<br>
            </P>
        </li>
        <li>
            <u>EffectCard Object Osztály:</u>
            <P>
                ECID : INT<br> Name : STRING<br>Image : IMAGE ICON<br>Description : STRIG<br> HpEffect : INT<br> ApEffect : INT<br> OtherEffect : STRING<br><br>
            </P>
        </li>
        <li>
            <u>SoundManager osztály:</u>
            <P>
                MusicVolume : INT<br> SoundVolume : INT<br> Mute : BOOLEAN<br>
            </P>
        </li>
        <li>
            <u>GroundCardObject Osztály:</u>
            <P>
                TKID : INT<br> Name : STRING<br> Image : IMAGE ICON<br> Description : STRING<br> TypeID : INT<br> DefPoint : INT<br> AtcPoint : INT<br> HealthPoint : INT<br>
            </P>
        </li>
        <li>
            <u>AirCardObject Osztály:</u>
            <P>
                TKID : INT<br> Name : STRING<br> Image : IMAGE ICON<br> Description : STRING<br> TypeID : INT<br> DefPoint : INT<br> AtcPoint : INT<br> HealthPoint : INT<br>
            </P>

        </li>
        <li>
            <u>Dealer Osztály:</u>
            <P>
                Cards : ArrayList(card)
                <br> Cristay :INT<br> NextCardIndex :INT<br>
            </P>
        </li>
        <li>
            <u>Deck Osztály:</u>
            <p>
                Cards : ArrayList(card)<br>
                <Card>
            </p>
        </li>
        <li>
            <u>DbContext Osztály:</u>
            <p>
                Ez az osztály csak metódusoakt tartalmaz.<br>
            </p>
        </li>
        <li>
            <u>CardUnitOfWork Osztály:</u>
            <p>
                Beolvassa az adatbázisból a szükséges adatokat ,és mikor a kártya meghívódik akkor példányosítódik, amit egy példányosító függvén hajt végre.<br>
            </p>

        </li>
        <li>
            <u>UserUnitOfWork Osztály:</u>
            <p>
                metódust tartalmaz amely az adatbázisból a szükséges adaatokat betölti az adott usernek.<br>
            </p>
        </li>
        <li>
            <u>ShopUnitOfWork Osztály:</u>
            <p>
                metódust tartalmaz amely az adatbázisból a szükséges adaatokat betölti az adott usernek.<br>
            </p>
        </li>
        <li>
            <u>LoginController Osztály:</u>
            <p>
                Username : STRING<br> Password : STRING<br>

            </p>
        </li>
        <li>
            <u>RegistrationController Osztály:</u>
            <P>
                Name : STRING<br> BirthDay : DATE<br> Username : STRING<br> Password : STRING<br> Email : STRING<br>
            </P>

        </li>
        <li>
            <u>MainMenuViewController Osztály:</u>
            <P>
                Login : BOOLEAN<br>
            </P>
        </li>
        <li>
            <u>HandController Osztály:</u>
            <p>
                Cristay : INT<br> CardInHand : INT<br>
            </p>
        </li>
        <li>
            <u>OptionsViewController Osztály:</u>
            <p>
                csak metódusokat tartalmaz.<br>
            </p>
        </li>
        <li>
            <u>PlayGroundViewController:</u>
            <p>
                Csak metódusokat tartalmaz.<br>
            </p>
        </li>
        <li>
            <u>PlayController Osztály:</u>
            <p>
                OnGroundCardDB : INT<br> BonusEffect : INT<br> RoundCounter : INT<br> WinPlayer : BOOLEAN<br> Matchbeg : DATE <br>RoundBeg : INT<br> RoundEnd : INT<br> MatchEnd : DATE
            </p>
        </li>
        <li>
            <u>CardDescriptionController osztály:</u>
            <P>
                Descripotion : STRING<br>
            </P>
        </li>
        <li>
            <u>ShopController osztály:</u>
            <p>
                Csak metódusoak tartalmaz.<br>
            </p>
        </li>
        <li>
            <u>UserData Manager:</u>
            <p>
                Csak metódusokat tartamaz.<br>
            </p>
        </li>
        <li>
            <u>OnGroundCardObject Osztály:</u>
            <p>
                CardDb : INT<br> Effected : BOOLEAN<br>
            </p>
        </li>
        <li>
            <u>DestroyedCardObject Osztály:</u>
            <p>
                Csak metódusokat tartalmaz.<br>
            </p>
        </li>
    </ul>
</body>

**Comment by MrDxD-SoulAdmin** [comment]
1.5óra
