### ISSUE TITLE
3.1.1 Kapcsolatok pontosítása

### ISSUE THREAD

**Issue by marcibaumel** [marcibaumel/SpeedCards#85]

**Comment by MrDxD-SoulAdmin** [comment]
bázisosztály csoportra bontás ábra

**Comment by MrDxD-SoulAdmin** [comment]
<body>
    <ul>
        <li>
            <u>MainMenuViewController:</u>
            <p>A MainMenuViewController a játék elindítása után, megjeleníti a GUI-t ami egy menürendszer. ebben a menürendszerben tudunk először bejelentkezni vagy regisztrálni amennyiben még nem regisztrált felhasználóról beszélünk. Miután a bejelentkwezés
                megtörténik ez a menürendszer lecserélődik , itt már látjuk az aktuális szintünket valamint innen tudunk új játékot indítani.
            </p>
            <img src="MenuController.png" style="border: 2px solid black; padding: 5px;">
        </li>
        <br>
        <li>
            <u>OptionViewController:</u>
            <p>
                Az optionViewController bejelentkezés után érhető majd el a MainMenuViewControllerből. A MainMenuViewControllerben van lehetőségünk ezt a gombot lenyombi és ezáltal hozzáférni a beállításokhoz. Itt van lehetőségünk a képernyő felbontást, a hangbeállításokat,
                useradatokat valamit paklit is módosítani. Useradatok alatt az avatar ,jelszó, név értendőek. A paklit is itt van lehetőségünk beállítani személyre szabni,és új egyedi paklit létrehozni az általunk birtokolt lapokból.
            </p>
            <img src="OptionModell.png" style="border: 2px solid black; padding: 5px;">
        </li>
        <br>
        <li>
            <ul>CardObject Osztály:</ul>
            <p>A cardObject oszály akkor lesz példnyosítva amikor egy játékmenet elindul. A cardObject osztály felelős a Ground(földi) és Air(légi) CardObjectek példányosításáért, valamint a játékos kezében levő lapok legenerálásáért. A cardobject osztály
                feladata ,hogyha egy lap el lesz használva vagy megsemmisül akkor ez az osztály egy "halott" laopt példányosít. </p>
            <img src="CardObjectMOdell.png" style="border: 2px solid black; padding: 5px;">
        </li>
        <br>
        <li>
            <u>DbContext Osztály:</u>
            <p>Ez az osztály az adatbázis és a program közötti adatkommunikációt biztosítsa. Az osztály amikor példányosítódik akkor az a példány az adatbázis egy meghatározott részét beolvassa és tárolja. Ebből az adatokat a UnitOfWork osztályok fogják
                kezelni. A UserUnitOfWork az adatból csak a user adatokat kezeli, a CardUnitOfWork osztály a kártyalapokkal kapcsolatos adatokat fogja kezelni,és a ShopUnitOfWork pedig a microtranzakciókat fogja kezelni az adathalmazból.
            </p>
            <img src="DbContext.png" style="border: 2px solid black; padding: 5px;">
        </li>

    </ul>
</body>

**Comment by MrDxD-SoulAdmin** [comment]
2óra
