### ISSUE TITLE
2.3. Alrendszerek

### ISSUE THREAD

**Issue by marcibaumel** [marcibaumel/SpeedCards#89]

**Comment by husoczkidani** [comment]
2.3 Alrendszerek

A Projekt több alrendszerre bontjuk, amik a funkcionálisan összetartozó osztályokat tartalmazzák.

1. controllers

Ez az alrendszer tartalmazza a Controller  osztályokat amelyek valamilyen eseményt kontrollálnak az alkalmazásban.

- CardController
- CartObjectController
- MainMenuViewController
- OptionsViewController
- PlayGroundViewController
- PlayController
- ShopController
- LoginController
- RegistrationController

2. media

A media osztály magába foglalja az alkalmazásban használt textúrákat és hangokat, amelyeket más osztályok felhasználnak.

- SoundManager

3. model

A model osztályban találhatjuk az alkalmazásban használt modell osztályokat, ilyen például a különböző fajta kártyák modelljei.

- AirCardObject
- CardObject
- Enemy
- GroundCardObject
- OnGroundCardObject
- DestroyedCardObject
- EffectCardObject
- Player

4. views

A views csoport tartalmazza az alkalmazásban lévő a grafikus megjelenítésre alkalmazott osztályokat.

- User
- Hand
- Deck
- Dealer
- DisplayManager
- mainMenuView
- optionsView
- playGroundView

5. dataAcces

Ebben az alrendszerben szerepelnek azok az osztályok, amellyekkel az alkalmazás kommunikál az adatbázissal.

- DbContext
- UserDataManager
- UserUnitOfWork
- ShopUnitOfWork
