### ISSUE TITLE
3.1. Adatbázis kezelő kiválasztása

### ISSUE THREAD

**Issue by marcibaumel** [marcibaumel/SpeedCards#97]

**Comment by kzsofia12** [comment]
Ezt az adatbázis rendszert MySQL rendszerben fogjuk kivitelezni, ennek eléréséhez pedig PHP MyAdmin felületet fogunk használni. Azért választottuk a MySQL rendszert mivel többfelhasználós és többszálon futó adatbázis kezelő rendszer és platform független vagyis minden platformon el tudja érni a software az adatok betöltésekor. Java nyelvből kezelhető a JDBC (Java DataBase Connectivity) segítségével. A JDBC egy API(Application Programming Interface) amely definiálja az adatbázisok lekérdezéséhez és módosításához szükséges osztályokat és metódusokat. A MySQL adatbázis eléréséhez azért választottunk PhpMyAdmin felületet mivel ez egy grafikus felület és könnyen átlátható ellentétben a consoleos(Parancssori) felülettel.
